description: >
  Needs:
    - GITHUB_ACCESS_TOKEN with a personal access token into it
    - GITHUB_USER_NAME
    - GITHUB_USER_EMAIL
steps:
  - run:
      name: config git to use GITHUB_ACCESS_TOKEN
      command: |
        git config --global url."https://${GITHUB_ACCESS_TOKEN}@github.com/".insteadOf "git@github.com:"
        git config --global user.email "${GITHUB_USER_NAME}"
        git config --global user.name "${GITHUB_USER_EMAIL}"
